<a href="https://colab.research.google.com/github/dzrich/GitPracDza/blob/main/IntroToPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [24]:
arr = np.array([[2,4,5],[4,6,8]])
print("Array:\n",arr)
print("Shape:\n", arr.shape)
print("Dimension:\n", arr.ndim)

Array:
 [[2 4 5]
 [4 6 8]]
Shape:
 (2, 3)
Dimension:
 2


In [25]:
arr.sort( axis=-1)

In [26]:
print(arr)


[[2 4 5]
 [4 6 8]]


In [16]:
a = np.array([1, 2, 3])
b = np.zeros((2, 2))
c = np.ones((2, 2))
d = np.arange(0, 10, 2)
e = np.empty((2, 2), dtype=int)

print("Matrix A \n", a, "\n Matrix B \n", b, "\n Matrix C \n", c, "\n Matrix D \n", d, "\n Matrix E \n", e)

Matrix A 
 [1 2 3] 
 Matrix B 
 [[0. 0.]
 [0. 0.]] 
 Matrix C 
 [[1. 1.]
 [1. 1.]] 
 Matrix D 
 [0 2 4 6 8] 
 Matrix E 
 [[          744696823                   0]
 [         4294967295 7310600471917625384]]


In [17]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [18]:
arr = np.array([10, 20, 30, 40])

print("First element:", arr[0])
print("Last element:", arr[-1])

First element: 10
Last element: 40


In [20]:
rr = np.array([1, 2, 3])

print("Add scalar:", arr + 5)

b = np.array([[1], [2], [3]])
c = np.array([10, 20, 30])
print("Shape:",b.shape)
print("Broadcasting result:\n", b + c)

Add scalar: [15 25 35 45]
Shape: (3, 1)
Broadcasting result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [1]:
from operator import itemgetter

# Example array
my_array = [[1, 5, 2], [3, 1, 8], [7, 9, 0]]

print("Original array:", my_array)

# Sort the array by the last element of each sub-array
sorted_array = sorted(my_array, key=itemgetter(-1))

print("Sorted array by last element:", sorted_array)

Original array: [[1, 5, 2], [3, 1, 8], [7, 9, 0]]
Sorted array by last element: [[7, 9, 0], [1, 5, 2], [3, 1, 8]]


#Analyzing Data Using Pandas

In [4]:
import pandas as pd
data = [10,20,30,40,50]
series =pd.Series(data)
print(series)
print("First Series:", series[0])
print("Last Series:", series[4])

0    10
1    20
2    30
3    40
4    50
dtype: int64
First Series: 10
Last Series: 50


#DataFrame in Pandas

In [10]:
import pandas as pd
data1= {"Age" : [34, 45, 56,55],
       "Name" : ["A", "B", "C", "D"]
}

df = pd.DataFrame(data1)
print(df)
print("Column Access:\n", df["Name"])

   Age Name
0   34    A
1   45    B
2   56    C
3   55    D
Column Access:
 0    A
1    B
2    C
3    D
Name: Name, dtype: object
